apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hergi2004/fullapp-argocd.git
    targetRevision: HEAD
    path: fullapp
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false